=== stagesoft/cuems-engine/dev/network_map.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="https://stagelab.coop/cuems" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cms="https://stagelab.coop/cuems">
    <xs:element name="CuemsNetworkMap">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="CuemsNodeDict" minOccurs="0" maxOccurs="1" type="cms:NodeDictType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="NodeDictType">
        <xs:sequence>
            <xs:element name="CuemsNode" minOccurs="0" maxOccurs="unbounded" type="cms:NodeType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="NodeType">
        <xs:sequence>
            <!-- <xs:element name="present" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/> -->
            <xs:element name="uuid" minOccurs="1" maxOccurs="1" type="xs:string"/>
            <xs:element name="mac" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/>
            <xs:element name="node_type" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/>
            <xs:element name="ip" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/>
            <xs:element name="port" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PutType">
        <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"></xs:element>
            <xs:element name="mappings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mapped_to" minOccurs="1" maxOccurs="unbounded" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:pattern value=".*[^\s].*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== stagesoft/cuems-engine/dev/test_xml_files/network_map.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsNetworkMap xmlns:cms="https://stagelab.coop/cuems/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://stagelab.coop/cuems/ https://stagelab.coop/cuems/network_map.xsd">
    <CuemsNodeDict>
        <CuemsNode>
            <uuid>0367f391-ebf4-48b2-9f26-000000000001</uuid>
            <mac>2cf05d21cca3</mac>
            <name>2cf05d21cca3._cuems_nodeconf._tcp.local.</name>
            <node_type>NodeType.master</node_type>
            <ip>192.168.1.10</ip>
            <online>True</online>
        </CuemsNode>
        <CuemsNode>
            <uuid>0367f391-ebf4-48b2-9f26-000000000003</uuid>
            <mac>0800276db133</mac>
            <name>0800276db133._cuems_nodeconf._tcp.local.</name>
            <node_type>NodeType.slave</node_type>
            <ip>192.168.1.101</ip>
            <online>False</online>
        </CuemsNode>
    </CuemsNodeDict>
</cms:CuemsNetworkMap>

=== stagesoft/cuems-engine/src/test_xml_files/network_map.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsNetworkMap xmlns:cms="http://stagelab.net/cuems"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://stagelab.net/cuems /etc/cuems/network_map.xsd">
    <CuemsNodeDict>
        <CuemsNode>
            <uuid>0367f391-ebf4-48b2-9f26-000000000001</uuid>
            <mac>2cf05d21cca3</mac>
            <name>2cf05d21cca3._cuems_nodeconf._tcp.local.</name>
            <node_type>NodeType.master</node_type>
            <ip>192.168.1.10</ip>
            <port>9000</port>
        </CuemsNode>
        <CuemsNode>
            <uuid>0367f391-ebf4-48b2-9f26-000000000003</uuid>
            <mac>0800276db133</mac>
            <name>0800276db133._cuems_nodeconf._tcp.local.</name>
            <node_type>NodeType.slave</node_type>
            <ip>192.168.1.101</ip>
            <port>9000</port>
        </CuemsNode>
    </CuemsNodeDict>
</cms:CuemsNetworkMap>

=== stagesoft/cuems-engine/dev/network_map.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsNetworkMap xmlns:cms="https://stagelab.coop/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stagelab.coop/cuems /etc/cuems/network_map.xsd">
    <CuemsNodeDict>
        <CuemsNode>
            <uuid>0367f391-ebf4-48b2-9f26-000000000001</uuid>
            <mac>jump._cuems_</mac>
            <name>jump._cuems_nodeconf._tcp.local.</name>
            <node_type>NodeType.master</node_type>
            <ip>172.17.0.1</ip>
            <port>9000</port>
        </CuemsNode>
    </CuemsNodeDict>
</cms:CuemsNetworkMap>
