=== stagesoft/cuems-engine/schemas/project_mappings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://stagelab.net/cuems" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cms="http://stagelab.net/cuems">
    <xs:element name="CuemsProjectMappings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="number_of_nodes" minOccurs="1" maxOccurs="1" type="xs:nonNegativeInteger" />
                <xs:element name="default_audio_input" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="default_audio_output" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="default_video_input" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="default_video_output" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="default_dmx_input" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="default_dmx_output" minOccurs="1" maxOccurs="1" type="xs:string" />
                <xs:element name="nodes" minOccurs="1" maxOccurs="1" type="cms:NodesType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="NodesType">
        <xs:sequence>
            <xs:element name="node" minOccurs="1" maxOccurs="unbounded" type="cms:NodeType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="NodeType">
        <xs:sequence>
            <xs:element name="uuid" minOccurs="1" maxOccurs="1" type="xs:string" />
            <xs:element name="mac" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString" />
            <xs:element name="audio" minOccurs="0" maxOccurs="1" type="cms:DeviceType" />
            <xs:element name="video" minOccurs="0" maxOccurs="1" type="cms:DeviceType" />
            <xs:element name="dmx" minOccurs="0" maxOccurs="1" type="cms:DeviceType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DeviceType">
        <xs:sequence>
            <xs:element name="outputs" minOccurs="0" maxOccurs="unbounded" type="cms:PutGroupType" />
            <xs:element name="inputs" minOccurs="0" maxOccurs="unbounded" type="cms:PutGroupType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PutGroupType">
        <xs:choice>
            <xs:element name="output" minOccurs="0" maxOccurs="unbounded" type="cms:PutType"/>
            <xs:element name="input" minOccurs="0" maxOccurs="unbounded" type="cms:PutType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="PutType">
        <xs:sequence>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="cms:NonEmptyString"></xs:element>
            <xs:element name="mappings">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="mapped_to" minOccurs="1" maxOccurs="unbounded" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MappedToType">
        <xs:sequence>
            <xs:element name="uuid" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
            <xs:element name="name" minOccurs="1" maxOccurs="1" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="NonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:pattern value=".*[^\s].*" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== stagesoft/cuems-engine/dev/test_xml_files/project_mappings.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsProjectMappings xmlns:cms="https://stagelab.coop/cuems/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stagelab.coop/cuems/ ../cuems/project_mappings.xsd">
    <number_of_nodes>2</number_of_nodes>
    <default_audio_input>2cf05d21cca3 system:capture_1</default_audio_input>
    <default_audio_output>2cf05d21cca3 system:playback_1</default_audio_output>
    <default_video_input />
    <default_video_output>2cf05d21cca3 0</default_video_output>
    <default_dmx_input />
    <default_dmx_output />
    <nodes>
        <node>
            <uuid>0367f391-ebf4-48b2-9f26-000000000001</uuid>
            <mac>2cf05d21cca3</mac>
            <audio>
                <outputs>
                    <output>
                        <name>system:playback_1</name>
                        <mappings>
                            <mapped_to>system:playback_1</mapped_to>
                            <mapped_to>Out1</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>system:playback_2</name>
                        <mappings>
                            <mapped_to>system:playback_2</mapped_to>
                        </mappings>
                    </output>
                </outputs>
                <inputs>
                    <input>
                        <name>system:capture_1</name>
                        <mappings>
                            <mapped_to>system:capture_1</mapped_to>
                        </mappings>
                    </input>
                    <input>
                        <name>system:capture_2</name>
                        <mappings>
                            <mapped_to>system:capture_2</mapped_to>
                        </mappings>
                    </input>
                </inputs>
            </audio>
            <video>
                <outputs>
                    <output>
                        <name>0</name>
                        <mappings>
                            <mapped_to>0</mapped_to>
                            <mapped_to>VideoOut1</mapped_to>
                            <mapped_to>VideoOut2</mapped_to>
                            <mapped_to>VideoOut3</mapped_to>
                            <mapped_to>VideoOut4</mapped_to>
                        </mappings>
                    </output>
                </outputs>
            </video>
            <dmx />
        </node>
        <node>
            <uuid>0367f391-ebf4-48b2-9f26-000000000003</uuid>
            <mac>0800276db133</mac>
            <audio>
                <outputs>
                    <output>
                        <name>system:playback_1</name>
                        <mappings>
                            <mapped_to>system:playback_1</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>system:playback_2</name>
                        <mappings>
                            <mapped_to>system:playback_2</mapped_to>
                        </mappings>
                    </output>
                </outputs>
            </audio>
            <video>
                <outputs>
                    <output>
                        <name>0</name>
                        <mappings>
                            <mapped_to>0</mapped_to>
                        </mappings>
                    </output>
                </outputs>
            </video>
            <dmx />
        </node>
    </nodes>
</cms:CuemsProjectMappings>

=== stagesoft/cuems-engine/src/test_xml_files/default_mappings.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsProjectMappings xmlns:cms="http://stagelab.net/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://stagelab.net/cuems /etc/cuems/project_mappings.xsd"><audio><outputs><output><name>system:playback_1</name><mappings><mapped_to>system:playback_1</mapped_to></mappings></output><output><name>system:playback_2</name><mappings><mapped_to>system:playback_2</mapped_to></mappings></output></outputs><default_output>system:playback_1</default_output><inputs><input><name>system:capture_1</name><mappings><mapped_to>system:capture_1</mapped_to></mappings></input><input><name>system:capture_2</name><mappings><mapped_to>system:capture_2</mapped_to></mappings></input></inputs><default_input>system:capture_1</default_input></audio><video><outputs><output><name>0</name><mappings><mapped_to>0</mapped_to></mappings></output><output><name>1</name><mappings><mapped_to>1</mapped_to></mappings></output></outputs><default_output>0</default_output></video><dmx /></cms:CuemsProjectMappings>

=== stagesoft/cuems-engine/dev/test_xml_files/default_mappings.xml
<?xml version='1.0' encoding='utf-8'?>
<cms:CuemsProjectMappings xmlns:cms="https://stagelab.coop/cuems/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://stagelab.coop/cuems/ /etc/cuems/project_mappings.xsd">
    <number_of_nodes>1</number_of_nodes>
    <default_audio_input>0367f391-ebf4-48b2-9f26-000000000001_system:capture_1</default_audio_input>
    <default_audio_output>0367f391-ebf4-48b2-9f26-000000000001_system:playback_1</default_audio_output>
    <default_video_input />
    <default_video_output>0367f391-ebf4-48b2-9f26-000000000001_0</default_video_output>
    <default_dmx_input />
    <default_dmx_output />
    <nodes>
        <node>
            <uuid>0367f391-ebf4-48b2-9f26-000000000001</uuid>
            <mac>2cf05d21cca3</mac>
            <audio>
                <outputs>
                    <output>
                        <name>system:playback_1</name>
                        <mappings>
                            <mapped_to>system:playback_1</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>system:playback_2</name>
                        <mappings>
                            <mapped_to>system:playback_2</mapped_to>
                        </mappings>
                    </output>
                </outputs>
                <inputs>
                    <input>
                        <name>system:capture_1</name>
                        <mappings>
                            <mapped_to>system:capture_1</mapped_to>
                        </mappings>
                    </input>
                    <input>
                        <name>system:capture_2</name>
                        <mappings>
                            <mapped_to>system:capture_2</mapped_to>
                        </mappings>
                    </input>
                </inputs>
            </audio>
            <video>
                <outputs>
                    <output>
                        <name>0</name>
                        <mappings>
                            <mapped_to>salida_001</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>1</name>
                        <mappings>
                            <mapped_to>salida_002</mapped_to>
                        </mappings>
                    </output>
                </outputs>
            </video>
            <dmx />
        </node>
        <node>
            <uuid>0367f391-ebf4-48b2-9f26-000000000002</uuid>
            <mac>2cf05d21cca3</mac>
            <audio>
                <outputs>
                    <output>
                        <name>system:playback_1</name>
                        <mappings>
                            <mapped_to>system:playback_1</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>system:playback_2</name>
                        <mappings>
                            <mapped_to>system:playback_2</mapped_to>
                        </mappings>
                    </output>
                </outputs>
                <inputs>
                    <input>
                        <name>system:capture_1</name>
                        <mappings>
                            <mapped_to>system:capture_1</mapped_to>
                        </mappings>
                    </input>
                    <input>
                        <name>system:capture_2</name>
                        <mappings>
                            <mapped_to>system:capture_2</mapped_to>
                        </mappings>
                    </input>
                </inputs>
            </audio>
            <video>
                <outputs>
                    <output>
                        <name>0</name>
                        <mappings>
                            <mapped_to>salida_001</mapped_to>
                        </mappings>
                    </output>
                    <output>
                        <name>1</name>
                        <mappings>
                            <mapped_to>salida_002</mapped_to>
                        </mappings>
                    </output>
                </outputs>
            </video>
            <dmx />
        </node>
    </nodes>
    <new_nodes></new_nodes>
</cms:CuemsProjectMappings>

=== stagesoft/cuems-engine/src/test_xml_files/project_mappings.xml
<?xml version="1.0" encoding="UTF-8"?>
<cms:CuemsProjectMappings xmlns:cms="http://stagelab.net/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://stagelab.net/cuems ../cuems/project_mappings.xsd">
    <audio>
        <outputs>
            <output>
                <name>system:playback_1</name>
                <mappings>
                    <mapped_to>Out1</mapped_to>
                </mappings>
            </output>
            <output>
                <name>system:playback_2</name>
                <mappings>
                    <mapped_to>Out2</mapped_to>
                </mappings>
            </output>
        </outputs>
        <default_output>system:playback_1</default_output>
    </audio>
    <video>
        <outputs>
            <output>
                <name>0</name>
                <mappings>
                    <mapped_to>VideoOut1</mapped_to>
                    <mapped_to>VideoOut3</mapped_to>
                </mappings>
            </output>
            <output>
                <name>1</name>
                <mappings>
                    <mapped_to>VideoOut2</mapped_to>
                    <mapped_to>VideoOut4</mapped_to>
                </mappings>
            </output>
        </outputs>
        <default_output>0</default_output>
    </video>
    <dmx>
    </dmx>
</cms:CuemsProjectMappings>
