=== stagesoft/cuems-engine/src/cuems/outputs.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://stagelab.net/cuems" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cms="http://stagelab.net/cuems">
    <xs:element name="CuemsOutputs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="video_outputs" type="cms:OutputsType" />
                <xs:element name="default_video_output" type="xs:string" />
                <xs:element name="audio_outputs" type="cms:OutputsType" />
                <xs:element name="default_audio_output" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- TYPES DEFINITIONS -->
    <xs:complexType name="OutputsType">
        <xs:sequence>
            <xs:element name="output" type="xs:string" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== stagesoft/cuems-engine/dev/test_xml_files/outputs.xml
<?xml version="1.0" encoding="UTF-8"?>
<cms:CuemsOutputs xmlns:cms="https://stagelab.coop/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://stagelab.coop/cuems ../cuems/outputs.xsd">
    <video_outputs>
        <output>0</output>
        <output>1</output>
    </video_outputs>
    <default_video_output>0</default_video_output>
    <audio_outputs>
        <output>system:playback_1</output>
        <output>system:playback_2</output>
    </audio_outputs>
    <default_audio_output>system:playback_1</default_audio_output>
</cms:CuemsOutputs>

=== stagesoft/cuems-engine/src/test_xml_files/outputs.xml
<?xml version="1.0" encoding="UTF-8"?>
<cms:CuemsOutputs xmlns:cms="http://stagelab.net/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://stagelab.net/cuems ../cuems/outputs.xsd">
    <video_outputs>
        <output>0</output>
        <output>1</output>
    </video_outputs>
    <default_video_output>0</default_video_output>
    <audio_outputs>
        <output>system:playback_1</output>
        <output>system:playback_2</output>
    </audio_outputs>
    <default_audio_output>system:playback_1</default_audio_output>
</cms:CuemsOutputs>
