=== stagesoft/cuems-engine/src/cuems/settings.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!-- describing schema for sample xml -->
<xs:schema targetNamespace="http://stagelab.net/cuems" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://stagelab.net/cuems">
    <xs:element name="Settings">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="node" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="osc_dest_host" type="NonEmptyString"></xs:element>
                            <xs:element name="oscquery_port" type="xs:positiveInteger"></xs:element>
                            <xs:element name="oscquery_out_port" type="xs:positiveInteger"></xs:element>
                            <xs:element name="engine_osc_in_port" type="xs:positiveInteger"></xs:element>
                            <xs:element name="engine_osc_out_port" type="xs:positiveInteger"></xs:element>
                            <xs:element name="websocket_port" type="xs:positiveInteger"></xs:element>
                            <xs:element name="videoplayer" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="path" type="NonEmptyString"></xs:element>
                                        <xs:element name="outputs" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="instance" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="osc_in_port" type="xs:positiveInteger"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="audioplayer" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="path" type="NonEmptyString"></xs:element>
                                        <xs:element name="audio_cards" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="instance" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="osc_in_port" type="xs:positiveInteger"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="dmxplayer" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="path" type="NonEmptyString"></xs:element>
                                        <xs:element name="universes" type="xs:positiveInteger"></xs:element>
                                        <xs:element name="instance" minOccurs="1" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="osc_in_port" type="xs:positiveInteger"></xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required"></xs:attribute>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="NonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
            <xs:pattern value=".*[^\s].*" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="UniqueID">
        <xs:restriction base="xs:int">
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== stagesoft/cuems-engine/src/cuems/settings.xml
<?xml version="1.0" encoding="UTF-8" ?>
<cms:Settings xmlns:cms="http://stagelab.net/cuems" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://stagelab.net/cuems settings.xsd">
    <node id="0" master="1">
        <osc_dest_host>localhost</osc_dest_host>
        <oscquery_port>7700</oscquery_port>
        <oscquery_out_port>7701</oscquery_out_port>
        <websocket_port>9092</websocket_port>
        <mtc_port>Midi Through Port-0</mtc_port>
        <videoplayer>
            <path>/usr/bin/xjadeo</path>
            <outputs>2</outputs>
            <instance id="0">
                <osc_in_port>7710</osc_in_port>
            </instance>
            <instance id="1">
                <osc_in_port>7720</osc_in_port>
            </instance>
        </videoplayer>
        <audioplayer>
            <path>/usr/bin/audioplayer</path>
            <audio_cards>1</audio_cards>
            <instance id="0">
                <osc_in_port>7730</osc_in_port>
            </instance>
        </audioplayer>
        <dmxplayer>
            <path>/path/to</path>
            <universes>1</universes>
            <instance id="0">
                <osc_in_port>7740</osc_in_port>
            </instance>
        </dmxplayer>
    </node>
</cms:Settings>
